# Generated by Django 3.2.7 on 2021-09-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210921_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignee',
            new_name='assignee_id',
        ),
    ]
