# Generated by Django 3.2.7 on 2021-09-22 14:50, related_name="related_tasks"

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rename_assignee_task_assignee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='owner',
            new_name='owner_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='status_id',
        ),
    ]
